= Shop API Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../doc/images/
Support Category: Select
Shop API Connector Version Major.Minor.Patch
// The Anypoint Connector for Shop API Connector provides ...
== About Shop API Connector

The Shop API Connector is an Operation Based Connector, which means that when you add the connector to your flow, you need to configure a specific operation the connector is intended to perform. 

The Shop API Connector enables the user to access the OCAPI by using certain configurations and access the data, update the data and delete the data if required.

The Open Commerce API (OCAPI) enables you to access resources using HTTP requests and HTTP responses. Each resource is addressed by its unique URL, which includes the API version. Data is transported using request or header parameters, or within the request body as a JSON document with a defined structure. 

OCAPI is divided into different APIs: the Shop API allows a client to interact with the system as a shop customer or as an agent shopping on behalf of a customer, the Data API gives Create, Read, Update and Delete access to system resources, and the Meta API is used to retrieve a formal description of the Open Commerce API, including custom attributes.

== Prerequisites

Before creating an app, you must have access to the Shop API Connector target resource and
Anypoint Platform. You also need understand how to create a Mule app using
Design Center or Anypoint Studio.

This document assumes that you are familiar with Mule, Anypoint Connectors,
Anypoint Studio Essentials, Mule flows, and Mule Global Elements.

To use Shop API Connector, you need

* Anypoint Studio version 7.
* shop-api.
* Credentials to access to Commerce cloud shop api back-office.

=== Mule Compatibility

[width="100%", options="header"]
|=======
|Application/Service |Version
|Mule Runtime |4 and later
|Anypoint Studio | 7 and later
|=======


== Audience
* Starting user -- To create your Mule app,
see xref:shop-api/shop-api-connector-design-center.adoc[Design Center Configuration]
or xref:shop-api/shop-api-connector-studio.adoc[Studio Configuration]. The
xref:shop-api/shop-api-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Shop API Connector. The
xref:shop-api/shop-api-connector-examples.adoc[Examples] topic provides one or more use
cases for using the connector.
* Power user - Read the xref:shop-api/shop-api-connector-xml-maven.adoc[XML and Maven
Support], xref:shop-api/shop-api-connector-config-topics.adoc[Additional Configuration Information], 
and xref:shop-api/shop-api-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector
Please check the xref:shop-api-connector-examples.adoc[Examples] link for the simple use case.


== Next Step

After you have met the prerequisites and experimented with templates and
examples, you are ready to create an app with
xref:shop-api/shop-api-connector-design-center.adoc[Design Center] or
xref:shop-api/shop-api-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=shop-api&type=connector[Anypoint
Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
